import { CaptionTemplateId, TextStyle } from '@/types/editor';

export interface CaptionTemplateConfig {
  id: CaptionTemplateId;
  name: string;
  tagline: string;
  previewSample: string;
  category: 'viral' | 'cinematic' | 'pop' | 'minimal';
  badgeColor: string;
  style: TextStyle;
}

export const CAPCUT_TEMPLATES: Record<CaptionTemplateId, CaptionTemplateConfig> = {
  karaoke: {
    id: 'karaoke',
    name: 'Karaoke Glow',
    tagline: 'Classic CapCut yellow active word pop',
    previewSample: 'CREATE VIRAL CONTENT',
    category: 'viral',
    badgeColor: '#EAB308',
    style: {
      captionTemplate: 'karaoke',
      fontFamily: 'Inter, sans-serif',
      fontSize: 46,
      fontWeight: '800',
      color: '#FFFFFF',
      activeWordColor: '#FFE500',
      activeWordScale: 1.15,
      inactiveOpacity: 0.85,
      outlineColor: '#000000',
      outlineWidth: 4,
      shadowColor: 'rgba(0,0,0,0.85)',
      shadowBlur: 10,
      textAlign: 'center',
      animationBounce: true,
    },
  },
  mrbeast: {
    id: 'mrbeast',
    name: 'MrBeast Impact',
    tagline: 'Heavy black stroke with explosive punch bounce',
    previewSample: 'HIGH IMPACT RETENTION',
    category: 'viral',
    badgeColor: '#FACC15',
    style: {
      captionTemplate: 'mrbeast',
      fontFamily: 'Impact, Montserrat, sans-serif',
      fontSize: 50,
      fontWeight: '900',
      color: '#FFFFFF',
      activeWordColor: '#FFDD00',
      activeWordScale: 1.2,
      inactiveOpacity: 0.9,
      outlineColor: '#000000',
      outlineWidth: 7,
      shadowColor: 'rgba(0,0,0,0.95)',
      shadowBlur: 14,
      textAlign: 'center',
      animationBounce: true,
    },
  },
  cinematic: {
    id: 'cinematic',
    name: 'Cinematic Pill',
    tagline: 'Frosted dark glass badge with ice blue accent',
    previewSample: 'Cinematic Documentary',
    category: 'cinematic',
    badgeColor: '#38BDF8',
    style: {
      captionTemplate: 'cinematic',
      fontFamily: 'Inter, sans-serif',
      fontSize: 38,
      fontWeight: '600',
      color: '#F8FAFC',
      activeWordColor: '#38BDF8',
      activeWordScale: 1.05,
      backgroundColor: 'rgba(15, 23, 42, 0.78)',
      boxPadding: 16,
      borderRadius: 14,
      letterSpacing: 0.8,
      shadowColor: 'rgba(0,0,0,0.5)',
      shadowBlur: 8,
      textAlign: 'center',
    },
  },
  neon: {
    id: 'neon',
    name: 'Cyber Neon',
    tagline: 'Electric cyan glow with white-hot active flash',
    previewSample: 'NEO CYBER VIBES',
    category: 'pop',
    badgeColor: '#00F0FF',
    style: {
      captionTemplate: 'neon',
      fontFamily: 'Inter, sans-serif',
      fontSize: 44,
      fontWeight: '800',
      color: '#00F0FF',
      activeWordColor: '#FFFFFF',
      activeWordScale: 1.15,
      outlineColor: '#0891B2',
      outlineWidth: 3,
      shadowColor: '#00F0FF',
      shadowBlur: 22,
      textAlign: 'center',
      animationBounce: true,
    },
  },
  boxed: {
    id: 'boxed',
    name: 'Boxed Badge',
    tagline: 'Dynamic yellow highlight pill following the speaker',
    previewSample: 'ACCENT HIGHLIGHT BOX',
    category: 'pop',
    badgeColor: '#F59E0B',
    style: {
      captionTemplate: 'boxed',
      fontFamily: 'Inter, sans-serif',
      fontSize: 42,
      fontWeight: '800',
      color: '#FFFFFF',
      activeWordColor: '#000000',
      activeWordBg: '#FACC15',
      activeWordScale: 1.08,
      backgroundColor: 'rgba(2, 6, 23, 0.65)',
      borderRadius: 8,
      boxPadding: 12,
      outlineColor: '#000000',
      outlineWidth: 2,
      textAlign: 'center',
    },
  },
  comic: {
    id: 'comic',
    name: 'Comic Bounce',
    tagline: 'Playful cartoon drop shadow and cheerful bounce',
    previewSample: 'SUPER FUN ANIMATION',
    category: 'pop',
    badgeColor: '#EC4899',
    style: {
      captionTemplate: 'comic',
      fontFamily: 'Arial Black, Inter, sans-serif',
      fontSize: 46,
      fontWeight: '900',
      color: '#FFED4A',
      activeWordColor: '#FF385C',
      activeWordScale: 1.18,
      outlineColor: '#0F172A',
      outlineWidth: 6,
      shadowColor: '#020617',
      shadowBlur: 6,
      textAlign: 'center',
      animationBounce: true,
    },
  },
  typewriter: {
    id: 'typewriter',
    name: 'Typewriter',
    tagline: 'Retro terminal sequential word typing cadence',
    previewSample: 'typing synchronized words...',
    category: 'minimal',
    badgeColor: '#A855F7',
    style: {
      captionTemplate: 'typewriter',
      fontFamily: 'Courier New, monospace',
      fontSize: 38,
      fontWeight: 'bold',
      color: '#F1F5F9',
      activeWordColor: '#22D3EE',
      backgroundColor: 'rgba(2, 6, 23, 0.85)',
      borderRadius: 8,
      boxPadding: 14,
      textAlign: 'center',
    },
  },
  'tiktok-single': {
    id: 'tiktok-single',
    name: 'TikTok Single Word',
    tagline: '1-word-at-a-time center punch for maximum retention',
    previewSample: 'PUNCH!',
    category: 'viral',
    badgeColor: '#22C55E',
    style: {
      captionTemplate: 'tiktok-single',
      fontFamily: 'Impact, Montserrat, sans-serif',
      fontSize: 64,
      fontWeight: '900',
      color: '#FFFFFF',
      activeWordColor: '#22C55E',
      activeWordScale: 1.25,
      outlineColor: '#000000',
      outlineWidth: 8,
      shadowColor: 'rgba(0,0,0,0.9)',
      shadowBlur: 16,
      textAlign: 'center',
      animationBounce: true,
    },
  },
};

export const TEMPLATE_LIST = Object.values(CAPCUT_TEMPLATES);

export function getTemplateConfig(id?: CaptionTemplateId): CaptionTemplateConfig {
  if (id && CAPCUT_TEMPLATES[id]) {
    return CAPCUT_TEMPLATES[id];
  }
  return CAPCUT_TEMPLATES.karaoke;
}
